env:
  global:
    - secure: "11NaOYU/73/9DzLNZUXw4jlpAvGtE1P7aU5yrMNfPbmTvAZR69ErAHoCxG1qNTpjkO7zmaP1hVRZoUY+rptBQGzk9ec3etngIJjW7E+XGb2SGtQniIA9DWzB4z0SiYxlC1b5BZ4xAeyrRHrTEVolIhCr/z0DHcCIrvO/NA4kiHfDLPHXyEUFiLnNGXcQtlgugUxEoTmW7fbUSwJVAnLZvGnS0fynzMjQjFG3BBVGQ4xFOb+usW+ANmN8+LFt7alvHT4KSBja2wBFgSE/+Zq5b++Lw+t5FubbFLVxS+455fj5MWROLz0YRXCb9/u8SFC3Osg3SxqGu/VXhwNqcag0ZV9yOS/ROJC+42JusgZJQnJe8jggeKMeAdof3rHUAvfwuj0sNXBimcDKkZIq+kgHtdMHKc5CcAXeCONx5V4iSEiPogyz/u5I0OXEqXXHh8OyxwRgW0afN0mpcTHRIHTGgEVDcAOyIfVq0WrwJzABD4Rb2LCK81qNIJcm8aXorTl3ASGgMFPBRneDl6Q8Y6P4JUUy1xapD5YqQZCqKuvT8XJWQhePa1DaCc+VoJtq8zLQZGC7X5ayvcrgC/kVFtVjjGdvd7Zb6YwQXhWUa2zTvzwZXwCpSqkhhjYMWYtf7ZohxO0HGwZRa27yI6JakUnqYWIH7PxAfQ1Hg72Efz4z+NA="
    - secure: "QUDvtfc9YGy5zbiCbqsbXu2oTKiIYUipQ/nksuVCNk1fQ0vzKT1L7spAu5v8ltUHBfbisGLjAhryeIQtZmHmPRWxeEtNV77Yn/HoFq+UiDh7r535BMnWRjNITo9mEv8r6iNVeSQJhtHvtncOoYZWop+6VncLn5IFSkNX1Sqf57lqGZKFt04mh1lk/qH2ApPsD+7v714khegVWmGqJXryXXKL2pKJSeHeD/7r6Z/O6EXM1VZKcDfFEGcEhypvzJe7IQFvCJEEBaddG6AGIKR7Q9In6qSXkhKx1arLuP1UQF4/naYkxkbYB6juwTioWzuAHuqrFRuRKyNHehU+mydlimqqAnNXAV0LC3dRHSNrSGjx+/XTqGr0Gb2qf4KwGHRRlGn/DxTNIa8NjgM3DOR/0DJaStEf8d8IhwGjFp0lf3WKrt+WSzsNQ76Zs7cDyoqPD+acN0q7/cAaNQZ4FBqg/yU9CWwfQ06voVGQVHkFGjLPR9YRc7G+PLSSJkK0BASCQnM8mkv6pZNNzf+5YkTUgwIWYVLKCOu2613tovx1xg/LZtzJhZtFppo926bEJL4Gw8sTtMKCcajv763t8Gjgdb7me1xqQHJN/ALRa3hMRj9lnKnMDQkkbQUoGFYCtZZUTiGVCPjYnhocfbrNExf4yCsnWJub2yAZt+RgtoiI/mo="

stages:
  - test
  - name: build_staging
    if: branch = development AND type = push
  - name: build_release
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      name: "xUnit Tests"
      language: csharp
      solution: user-groups.sln
      mono: none
      dotnet: 2.1
      script:
        - dotnet restore
        - dotnet test UserGroupsTest/UserGroupsTest.csproj
    - stage: build_staging
      name: "Build docker staging image"
      sudo: required
      services:
        - docker
      script:
        - ./bin/docker.sh staging
    - stage: build_release
      name: "Build docker release image"
      sudo: required
      services:
        - docker
      script:
        - ./bin/docker.sh latest

notifications:
    slack: sem5640-2018:B3KKIVa9nY0Z37nr1VY5vUFS
