openapi: 3.0.0
info:
  description: "User-Groups API."
  version: "1.0.0"
  title: "User-Groups API"
  
tags:
- name: "group"
  description: "Request the members of a given group"
- name: "user"
  description: "Describes the group a member belongs to if any"
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme : bearer

# Apply security globally  
security:
  - bearerAuth: []
      
    
paths: 
  /group/{groupId} :
    get:
      tags: [group]
      summary: Returns all members matching the given group ID
      parameters:
      - in: path
        name: groupId
        required: true
        schema:
          type: string
        description: The group's unique ID to lookup
      responses:
        200:
          description: "The user IDs which belong to this group"
        401:
          description: "Unauthorised"
        404:
          description: "The requested group does not exist"
        500:
          description: "Internal server error"
  /group/all :
    get:
      tags: [group]
      summary: Returns all groups
      responses:
        200:
          description: "All group IDs"
        401:
          description: "Unauthorised"
        500:
          description: "Internal server error"
  
  /user/{userId} :
      get:
        tags: [user]
        summary: Returns the group which a user belongs to
        parameters:
          - in: path
            name: userId
            required: true
            schema:
              type: string
              description: The user ID to lookup
        responses:
          200:
            description: "The groups this user ID belongs to, if any."
          401:
            description: "Unauthorised"
          404:
            description: "The requested user does not exist"
          500:
            description: "Internal server error"